// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0HS0gqgwBid2PiQzkVstlJJmf-wqj9G4',
    appId: '1:62022410637:web:d99d2bda8a08ebd7301dc4',
    messagingSenderId: '62022410637',
    projectId: 'electricityplus-a6572',
    authDomain: 'electricityplus-a6572.firebaseapp.com',
    storageBucket: 'electricityplus-a6572.appspot.com',
    measurementId: 'G-7PK7819R9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjsjIQBuJQ_YafX2GseFWbBcTHC94aiIQ',
    appId: '1:62022410637:android:dc187a9d0a8d5ee6301dc4',
    messagingSenderId: '62022410637',
    projectId: 'electricityplus-a6572',
    storageBucket: 'electricityplus-a6572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRUsi6oUXpsBVgtIGCYsEnhR8hOYlsZtE',
    appId: '1:62022410637:ios:0559259b41453309301dc4',
    messagingSenderId: '62022410637',
    projectId: 'electricityplus-a6572',
    storageBucket: 'electricityplus-a6572.appspot.com',
    iosClientId: '62022410637-st7oqr3p4j2vq8ht1vbuogf1adi36rc0.apps.googleusercontent.com',
    iosBundleId: 'com.electricityplus.electricityPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRUsi6oUXpsBVgtIGCYsEnhR8hOYlsZtE',
    appId: '1:62022410637:ios:0559259b41453309301dc4',
    messagingSenderId: '62022410637',
    projectId: 'electricityplus-a6572',
    storageBucket: 'electricityplus-a6572.appspot.com',
    iosClientId: '62022410637-st7oqr3p4j2vq8ht1vbuogf1adi36rc0.apps.googleusercontent.com',
    iosBundleId: 'com.electricityplus.electricityPlus',
  );
}
